@startuml
'https://plantuml.com/class-diagram

class ThanhPhanChuoi {
    String tenGiai;
    List<String> boSoTrungThuong;

    + {abstract} ThanhPhanChuoi thietLapKeTiep(ThanhPhanChuoi k)
    + {abstract} String doVeSo(String veSo)

}

class GiaiThapNhat {

}

class GiaiThuong {

}

ThanhPhanChuoi <|-- GiaiThapNhat
ThanhPhanChuoi <|-- GiaiThuong
GiaiThuong --> ThanhPhanChuoi : ketiep

@enduml